### PR TITLE
Avoid unnecessary effect calls due to use-fullscreen

### PR DESCRIPTION
**Pull request by AdrienLemaire**
useFullscreen returns new functions whenever it is being called. That means that every useEffect that uses a function from useFullscreen will be re-executed.
This created issues for us (duplicate notifications sent from said useEffect).

The solution is to return a memoized function by using useCallback.
Haven't looked at other hooks, but I'm afraid this problem is not only affecting this hook...

### CODE REVIEW

**Comment by imbhargav5** [comment]
Going to get to this after I get home tonight. Thanks!

**Review by maciekgrzybek — APPROVED** [review]

**Comment by imbhargav5** [comment]
@maciekgrzybek Is this tested?

**Comment by maciekgrzybek** [comment]
No I haven't tested it

**Comment by imbhargav5** [comment]
Thanks @AdrienLemaire !!

**Pull request merged**
