### PR TITLE
Added package table of contents.

### PR DESCRIPTION
**Pull request by justinformentin**
I added a table of contents to more easily jump to specific packages in the README, and slightly reorganized a couple of things.

### CODE REVIEW

**Comment by imbhargav5** [comment]
This is an excellent start. Will review it once I wake up!

**Comment by imbhargav5** [comment]
@justinformentin Since the readme is autogenerated right now, it will get overridden by the autogeneration logic for the next time. Can we add the package table of contents to this file instead? 
https://github.com/imbhargav5/rooks/blob/master/helpers/update_readme.js
And then, `node helpers/update_readme` from the root of the project. It will generate a new Readme with the changes. 

Also, to move `rooks` package to the top, we will need to update the same `update_readme.js` file to make sure that `rooks` package has more importance than the rest.

**Comment by justinformentin** [comment]
Makes sense!

**Comment by imbhargav5** [comment]
Hey @justinformentin I made some changes to the readme to ensure that we can just update the Readme file instead of update_readme script. Do you want to make any changes to the current readme?

**Comment by justinformentin** [comment]
Nope, looks good!

**Comment by imbhargav5** [comment]
I feel bad that this PR has gotten stale. 😓 Would you like to try another issue @justinformentin ?

**Pull request closed without merging**
