### PR TITLE
feat:  useClickAndHold hook

### PR DESCRIPTION
**Pull request by jefersonvinicius**
I created a simple new hook that give the ability of click and hold.

### CODE REVIEW

**Comment by imbhargav5** [comment]
@jefersonvinicius Awesome hook! Could you explain more about what this hook can do here for context as I review it?

**Comment by jefersonvinicius** [comment]
> > I would like add some codesandbox, but I haven't sure if the pull request should be merged first to be able install rooks lib in codesandbox with this hook available.
> 
> Hi @jefersonvinicius, I guess you could copy this hook's source code to codesandbox and create an example first. Later after this hook is published we will help update the codesandbox!

I'll do it. Thanks for the suggestion. I'm making some improvements as well!

**Comment by jefersonvinicius** [comment]
Hey, it's everything alright :D

**Comment by hooriza** [comment]
It's cool!
How about using [the pointer events](https://caniuse.com/pointer)?

**Pull request closed without merging**
