### PR TITLE
Disable useWindowEventListener warning logs in production.

### PR DESCRIPTION
**Pull request by AbdallahAbis**
This hook currently clutters logs on SSR.

### CODE REVIEW

**Comment by imbhargav5** [comment]
Ah. This is a great catch. We actually have a hook for this. I would appreciate greatly if you use the `useWarningOnMountInDevelopment ` and just put this message to log in development on mount.

**Comment by AbdallahAbis** [comment]
@imbhargav5 I don't see any docs for the hook, and also Rooks don't have a named export `useWarningOnMountInDevelopment`?

**Comment by imbhargav5** [comment]
Ah I should have explained this better. Apologies. We have an internal util . It's not for external use. Hence not exported. I am on mobile, let me link the actual file here.

**Comment by imbhargav5** [comment]
Here is the link - https://github.com/imbhargav5/rooks/blob/c669a8eb841b0d74218365526b5182adae658443/src/hooks/useWarningOnMountInDevelopment.ts

**Comment by imbhargav5** [comment]
On further thought, I think that warning itself is completely useless as it is running in the render phase. I think it's best to remove the warning and warn within `useGlobalEventListener` effect phase.

**Comment by imbhargav5** [comment]
https://github.com/imbhargav5/rooks/issues/836 Here is the issue corresponding to this. If you would like to contribute, please take a shot, else, I will get to it tomorrow! Many thanks!

**Comment by imbhargav5** [comment]
Closing as this is resolved.

**Pull request closed without merging**
