### PR TITLE
implement useToggle with useReducer

### PR DESCRIPTION
**Pull request by dancerphil**

### CODE REVIEW

**Comment by imbhargav5** [comment]
@dancerphil This is really good. ❤️ 
Can you add a test case to show usage with a reducer?

**Comment by dancerphil** [comment]
Sure.

**Comment by imbhargav5** [comment]
I changed the base to `dev` on which I am making a few changes to how the hooks to be more presentable. Please rebase off it :)

**Comment by imbhargav5** [comment]
😄 Merged with commits 3747f5efc951089869d287fe33dd9aedb166bc28 and added test cases here d809e6e4589ff0c4c0df3abb35973912cdc37536.

**Pull request closed without merging**
