### PR TITLE
fix: build fail

### PR DESCRIPTION
**Pull request by qiweiii**

### CODE REVIEW

**Comment by imbhargav5** [comment]
Is docusaurus build working fine now?

**Comment by qiweiii** [comment]
> Is docusaurus build working fine now?

yep

**Comment by imbhargav5** [comment]
Looks fantastic @qiweiii . I would like to add just one thing to this PR. 

Right now, I configured mergify to automatically merge dependabot  PR if CI succeeds. Can we force dependabot to not update these problematic packages by using the `ignore` config as shown here? 

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore

**Comment by qiweiii** [comment]
@imbhargav5 added to dependentbot config

**Pull request merged**
