### PR TITLE
update use did update

### PR DESCRIPTION
**Pull request by zeritte**
In the past, useDidUpdate didn't run the cleanup function of the callback.

```
useDidUpdate(() => {
   API.subscribe(userID)
   ()  => API.unsubscribe(userID)
}, [userID])
```

Before the PR, unsubscribe function is never called. With the PR, it will be called properly

### CODE REVIEW

**Comment by zeritte** [comment]
https://github.com/streamich/react-use/blob/master/src/useUpdateEffect.ts similar approach

**Comment by imbhargav5** [comment]
Actually that was intentional. I wanted it to look very similar to componentDidUpdate which doesn't have a cleanup. Perhaps we can do another hook like `useUpdateEffect`or something? Would love if you want to do a PR for that instead!

**Comment by zeritte** [comment]
I created useUpdateEffect but I think we should have merged it with useDidUpdate instead. If a user wants to use a cleanup, he can. If he doesn't want to use a cleanup like componentDidUpdate, he doesn't have to.

For useUpdateEffect function, svg file and codesandbox.io example are missing

**Comment by imbhargav5** [comment]
Yeah the only reason why I am thinking of a different hook is because I don't want to cause breaking changes if someone is using useDidUpdate with async. That would break if we put in a cleanup since async functions return a promise but cleanup needs to be a function.

**Comment by zeritte** [comment]
OK I see your point

**Comment by zeritte** [comment]
@imbhargav5 hey, did you have a chance to look at this?

**Comment by imbhargav5** [comment]
Hi I am resting right now. Will be back in a week. Thanks for your
patience.

**Comment by imbhargav5** [comment]
Going to add test cases and merge today!

**Comment by imbhargav5** [comment]
@all-contributors please add @zeritte for code.

**Pull request closed without merging**
