### PR TITLE
Feature/outside click hook update

### PR DESCRIPTION
**Pull request by maciekgrzybek**
Pull request for #86. I've also added some instructions into contributing file.

### CODE REVIEW

**Comment by imbhargav5** [comment]
@maciekgrzybek Everything looks good. Except the useEffect which has savedCallback.

**Comment by maciekgrzybek** [comment]
Hmm, but the only time when `savedCallback.current` should be updated, would be the change of `handler` right? So it could live all in one `useEffect`. Don't take that as an attack or something :) just want to understand what's going on :)

**Comment by maciekgrzybek** [comment]
Also, wouldn't `useCallback` be a good choice in this example? - https://reactjs.org/docs/hooks-reference.html#usecallback

**Comment by maciekgrzybek** [comment]
I did some testing, both with single useEffect and with useCallback:
```
  const memoizedCallback = useCallback(
    (e) => {
      handler(e);
    },
    [],
  );
```
and it works fine in both cases. It always passes the correct event object (correct target). But maybe I'm missing something? Let me know, thanks :)

**Comment by imbhargav5** [comment]
@maciekgrzybek I remember thinking about useCallback but I had to go for a ref for a reason I can't seem to remember. Let me see if I can reproduce the issue.

**Comment by imbhargav5** [comment]
So useCallback will result in an unnecessary rerender which we don't need. We only need to update the function and not worry about rerender. And refs can update without rerender. So we should stick to `ref` when it comes to the savedCallback.
As far as the `savedCallback` in the same useEffect is concerned, you are right, I think putting in the same useEffect will be fine. Also, can you do one more change? I think `handle` can be within a useCallback.

**Comment by maciekgrzybek** [comment]
Hey, @imbhargav5 I've just pushed the changes, hope that was what you were thinking about :)

**Comment by imbhargav5** [comment]
Yep. Looks good. ❤️  It's a nuance but can you move memoized callback definition right before the useEffect and I will merge this.

**Comment by maciekgrzybek** [comment]
Done :)

**Pull request merged**
