### PR TITLE
contributors file added in docs

### PR DESCRIPTION
**Pull request by Avi98**
Related to #313

- [x] added contributors.md inside docs
- [ ] update GitHub workflow update-title-card

### CODE REVIEW

**Comment by imbhargav5** [comment]
So, the important part of this issue is to make sure we run this everyday as a GitHub action. So you can take a look at a couple of other GitHub workflows we already have that run once a day. 

The idea is that we run this task once every 1 or 2 days and make sure this contributors list is always upto date. What say?

**Comment by Avi98** [comment]
> So, the important part of this issue is to make sure we run this everyday as a GitHub action. So you can take a look at a couple of other GitHub workflows we already have that run once a day.
> 
> The idea is that we run this task once every 1 or 2 days and make sure this contributors list is always upto date. What say?
> 
> So similar to update-title-card, we will have to create another GitHub workflow that runs once every 2 days.



> So, the important part of this issue is to make sure we run this everyday as a GitHub action. So you can take a look at a couple of other GitHub workflows we already have that run once a day.
> 
> The idea is that we run this task once every 1 or 2 days and make sure this contributors list is always upto date. What say?
> 
> So similar to update-title-card, we will have to create another GitHub workflow that runs once every 2 days.

Yes @imbhargav5 , will try to complete by tomorrow EOD.
Thanks a lot for looking into my PR

**Comment by imbhargav5** [comment]
I must be thanking you. Thanks for this work man!

**Comment by Avi98** [comment]
Hi @imbhargav5, I'm new to github actions. Can I add a job to existing workflow ```update-title-card```  as it already runs after every two days. The job will be something similar to this

```yml
- name: update-contributors-list
        run: yarn run contributors:generate
```

**Comment by imbhargav5** [comment]
@Avi98 For sure. Sorry I responded late.

**Pull request closed without merging**
