### PR TITLE
Feature/use throttle hook

### PR DESCRIPTION
**Pull request by maciekgrzybek**

### CODE REVIEW

**Comment by imbhargav5** [comment]
Looks solid !! Going to merge it after I review it again.

**Comment by maciekgrzybek** [comment]
nice one :)

**Comment by imbhargav5** [comment]
I think we might need to change the hook's logic. Because setTimeout is hanging in there without a way to clear it.

**Comment by maciekgrzybek** [comment]
What if I put logic inside of useEffect, so I could clear it there?

**Comment by imbhargav5** [comment]
@maciekgrzybek Yes that's right. We need to figure out a way to put in the logic in the useEffect and clear the timeout in the cleanup part of the useEffect.

**Comment by imbhargav5** [comment]
Oops accidentally closed it.

**Comment by maciekgrzybek** [comment]
Hey, @imbhargav5 I've made the change, should be all right now :)

**Comment by imbhargav5** [comment]
Hmmm, I think we need to work on the logic a bit more. let me come up with something and explanation for it on Monday.

**Comment by maciekgrzybek** [comment]
Ok, what's wrong?

**Comment by imbhargav5** [comment]
Let's track this in a different branch `feat/use-throttle`

**Pull request merged**
