### PR TITLE
window-size: Fix TS definitions and add tests

### PR DESCRIPTION
**Pull request by ankithkonda**
Old TS definition used width and height instead of innerWidth and innerHeight. Thought I would also add tests as well. This is my first time writing tests for hooks, please let me know if i need to make any improvements :)

### CODE REVIEW

**Comment by ankithkonda** [comment]
hi @imbhargav5 seems like the hooks I didn't make changes to are failing? even though the "build passing" badge is displayed in the readme. suggestions?

**Comment by imbhargav5** [comment]
Hey @ankithkonda Thanks for this PR. Can you please rebase this on `dev` branch. I put in a lot of work by adding types, storybook and more bug fixes. And we can add your changes onto that :)

**Comment by ankithkonda** [comment]
No worries, I'll close this pull request for now and open another one for dev branch :)

**Comment by imbhargav5** [comment]
I merged dev into master recently because i am nearly done with updates, so just pull in master once again and reopen :)

**Pull request closed without merging**
